---
apiVersion: tower.ansible.com/v1alpha1
kind: AnsibleJob
metadata:
  name: demo-job-002
  namespace: simon-ansible
  labels:
    app.kubernetes.io/name: hello-simon
spec:
  tower_auth_secret: toweraccess
  job_template_name: acm-stuff
#  extra_vars:
#    cost: 6.88
#    ghosts: ["inky","pinky","clyde","sue"]
#    is_enable: false
#    other_variable: foo
#    pacman: mrs
#    size: 8
#    targets_list:
#    - aaa
#    - bbb
#    - ccc
#    version: 1.23.45
